### ISSUE TITLE
Charm incompatibility (Quilt 1.19.2)

### ISSUE THREAD

**Issue by Blu-Team** [sisby-folk/tinkerers-smithing#11]
Tinkerer's Smithing (verison 2.2.4) is incompatible with Charm (version 4.4.4).

Log: https://mclo.gs/qsmOumA
Quilt log: https://mclo.gs/pCYTHlw

Charm github post: https://github.com/svenhjol/Charm/issues/918
Quilt forum post: https://forum.quiltmc.org/t/tinkers-smithing-incompatibility-1-19-2/1399

**Comment by sisby-folk** [comment]
Yeah there's a colliding redirect mixin for getRepairMaterials. Tinkerer's Smithing completely replaces the list of repair materials generated for the anvil with its own data-driven list. 

Last I checked charm messes with the anvil as well - feel free to list the features charm has that touch the anvil, and I can probably extrapolate which one collides from there.

Because Tinkerer's Smithing's core feature is completely replacing anvil repair materials, this redirect is fairly deliberate - it *shouldn't* stack with another repair materials replacer, so this crash is ideal - there are other ways to achieve similar-to-repair behaviour for added crafting recipes which *does* stack, which we use to add our anvil de-working recipe.

Charm is MIT, so I'll say here that they have full unrelenquishable permission to derive from [this non-redirecting mixin](https://github.com/sisby-folk/tinkerers-smithing/blob/1.19/src/main/java/folk/sisby/tinkerers_smithing/mixin/AnvilScreenHandlerMixin.java#L73) if they are in fact trying to add a new anvil recipe type.

If charm is instead just adding a feature that TSmithing shadows over (making netherite repairable with diamond, making chain repairable with chain, etc) I'd recommend they just use a mixin plugin to turn it off when TSmithing is present - they shouldn't both run at once.

**Comment by Blu-Team** [comment]
> Last I checked charm messes with the anvil as well - feel free to list the features charm has that touch the anvil, and I can probably extrapolate which one collides from there.

Thanks for replying and yes charm does mess with anvils. See https://svenhjol.github.io/Charm/sections/smithing for all the features that mess with them. I can try disabling some of the features in charm to see if I can get it to work. I'll edit this after I test.

Edit: Nope, couldn't get them to work. I tried disabling all the anvil features and still crashes.

**Comment by sisby-folk** [comment]
fixed in 2.6 by using wrap and modifyexpression instead of redirects

**Comment by Blu-Team** [comment]
> fixed in 2.6 by using wrap and modifyexpression instead of redirects

ty
