### ISSUE TITLE
Recipes break when using KubeJS

### ISSUE THREAD

**Issue by mintynoura** [sisby-folk/tinkerers-smithing#40]
So I'm using the mods on Quilt 1.20.1, and it seems that using startup scripts from KubeJS to modify or register anything (not necessarily related to anvils/smithing) will disable all the crafting and smithing recipes from Tinkerer's Smithing, as well as break the anvil repairing mechanics. Enchanting with books, combining tools, and using netherite scrap to reduce repair cost still work fine though

![image](https://github.com/sisby-folk/tinkerers-smithing/assets/107040228/f4aeed8d-2911-4a9d-a501-bf90cb937c71)

![image](https://github.com/sisby-folk/tinkerers-smithing/assets/107040228/8dd5da10-53e8-4949-a344-1b6577d87445)

Neither the minecraft logs nor the KubeJS logs mention any errors

**Comment by sisby-folk** [comment]
The relevant mixins that kubejs must be breaking are [SimpleResourceReloadMixin](https://github.com/sisby-folk/tinkerers-smithing/blob/1.19/src/main/java/folk/sisby/tinkerers_smithing/mixin/SimpleResourceReloadMixin.java) and/or [RecipeManagerMixin](https://github.com/sisby-folk/tinkerers-smithing/blob/1.19/src/main/java/folk/sisby/tinkerers_smithing/mixin/RecipeManagerMixin.java).

In order to create data-driven recipes, Tinkerer's Smithing carefully registers its reloaders before recipes reload (which isn't exposed as an option by fabric api) - in all likelihood, kubejs is reordering reloaders after the fact, causing 0 recipes to be loaded. 

We generally don't recommend kubejs precisely because its invasive patchset tends to break mods, so you can file the issue there if you like - there's nothing we can do on this side afaik.

**Comment by mintynoura** [comment]
That's a shame. Thank you for the quick response! I'll experiment with
CraftTweaker and see if it works out
